import { StyleSheet } from 'react-native';
import palette from '../../assets/theme/theme';
import { horizontalScale, moderateScale, verticalScale } from '../../assets/metrics/metrics';

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: palette.primary_blue,
    },
    title: {
        width: horizontalScale(160),
        textAlign: 'center',
        fontSize: moderateScale(20),
        marginHorizontal: horizontalScale(110),
        marginTop: verticalScale(50),
        color: palette.white,
    },
    contain: {
        marginHorizontal: horizontalScale(10),
        marginVertical: verticalScale(80),
        position: 'relative',
    },
    averageFemaleBodyURL: {
        width: horizontalScale(354),
        height: verticalScale(372),
    },
    shoulderRingURL: {
        width: horizontalScale(149),
        height: verticalScale(17),
        position: 'absolute',
        top: verticalScale(70),
        right: horizontalScale(103),
    },
    waistRingURL: {
        width: horizontalScale(90),
        height: verticalScale(10),
        position: 'absolute',
        top: verticalScale(140),
        right: horizontalScale(132),
    },
    hipRingURL: {
        width: horizontalScale(132),
        height: verticalScale(15),
        position: 'absolute',
        top: verticalScale(190),
        right: horizontalScale(111),
    },
    button: {
        width: horizontalScale(171),
        height: verticalScale(70),
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: verticalScale(40),
        marginHorizontal: horizontalScale(105),
        marginVertical: verticalScale(15),
        marginTop: verticalScale(20),
        backgroundColor: palette.light_blue,
    },
    textBtn: {
        fontSize: moderateScale(16),
        textAlign: 'center',
        color: palette.white,
    },
    again: {
        textDecorationLine: "underline",
        textDecorationStyle: "solid",
        textDecorationColor: palette.white,
    },
    shoulder: {
        width: horizontalScale(100),
        height: verticalScale(50),
        zIndex: 2,
        position: 'absolute',
        top: verticalScale(10),
        right: horizontalScale(40),
    },
    shoulderSize: {
        width: horizontalScale(60),
        height: verticalScale(30),
        fontSize: moderateScale(15),
        textAlign: 'center',
        borderRadius: verticalScale(10),
        padding: verticalScale(5),
        left: horizontalScale(15),
        backgroundColor: palette.light_blue,
        color: palette.white,
    },
    shoulderText: {
        width: horizontalScale(100),
        height: verticalScale(50),
        fontSize: moderateScale(17),
        textAlign: 'left',
        color: palette.white,
    },
    waist: {
        width: horizontalScale(100),
        height: verticalScale(50),
        zIndex: 2,
        position: 'absolute',
        top: verticalScale(120),
        right: verticalScale(199),
    },
    waistSize: {
        width: horizontalScale(60),
        height: verticalScale(30),
        fontSize: moderateScale(15),
        textAlign: 'center',
        borderRadius: verticalScale(10),
        padding: verticalScale(5),
        left: 0,
        backgroundColor: palette.light_blue,
        color: palette.white,
    },
    waistText: {
        width: horizontalScale(100),
        height: verticalScale(50),
        fontSize: moderateScale(17),
        textAlign: 'left',
        left: horizontalScale(10),
        color: palette.white,
    },
    hip: {
        width: horizontalScale(100),
        height: verticalScale(50),
        zIndex: 2,
        position: 'absolute',
        top: verticalScale(180),
        right: horizontalScale(-15),
    },
    hipSize: {
        width: horizontalScale(60),
        height: verticalScale(30),
        fontSize: moderateScale(15),
        textAlign: 'center',
        borderRadius: verticalScale(10),
        padding: verticalScale(5),
        left: 0,
        backgroundColor: palette.light_blue,
        color: palette.white,
    },
    hipText: {
        width: horizontalScale(100),
        height: verticalScale(50),
        fontSize: moderateScale(17),
        textAlign: 'left',
        color: palette.white,
        left: horizontalScale(12),
    }
});

export default styles;
